### ISSUE TITLE
EPERM, mkdir

### ISSUE THREAD

**Issue by oriharel** [jxcore/jxcore-ios-sample#1]
In my JS code ran by JXcore, I'm saving files and creating folders, using require('tar'):

``` javascript
var tar = require("tar");
var tarExtractor = tar.Extract({path: __dirname + "/extract"})
```

But I get permission error:

{ [Error: EPERM, mkdir '/private/var/mobile/Containers/Bundle/Application/B4C68C28-0AD2-494F-BC8F-A711B1590FEA/Local.app/JS/jxcore/extract']
  message: 'EPERM, mkdir \'/private/var/mobile/Containers/Bundle/Application/B4C68C28-0AD2-494F-BC8F-A711B1590FEA/Local.app/JS/jxcore/extract\'',
  errno: 50,
  code: 'EPERM',
  path: '/private/var/mobile/Containers/Bundle/Application/B4C68C28-0AD2-494F-BC8F-A711B1590FEA/Local.app/JS/jxcore/extract',
  fstream_type: 'Directory',
  fstream_path: '/private/var/mobile/Containers/Bundle/Application/B4C68C28-0AD2-494F-BC8F-A711B1590FEA/Local.app/JS/jxcore/extract',
  fstream_class: 'DirWriter',
  fstream_stack: 
   [ 'mkdirP/</<@/private/var/mobile/Containers/Bundle/Application/B4C68C28-0AD2-494F-BC8F-A711B1590FEA/Local.app/JS/jxcore/node_modules/tar/node_modules/fstream/node_modules/mkdirp/index.js:47:53',
     'makeCallback/<@fs.js:84:12',
     '' ] }

Any idea how can I overcome this?

**Comment by oriharel** [comment]
I think I have a clue - I'm trying to save files into '/private/var/mobile/Containers/Bundle/Application/... folder, instead of /var/mobile/Containers/Data/Application/. which is more likely the place. I'll try that. in the Android sample you had the process.cwd = "..." from jxcore.java. I just need to find the equivalent in iOS

**Comment by obastemur** [comment]
See https://github.com/jxcore/jxcore-cordova#where-to-save-your-files-write-access-on-mobile-targets-erofs-error-

**Comment by oriharel** [comment]
yup. I did:

``` objective-c
NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
NSString *documentsDirectory = [paths objectAtIndex:0];NSArray *directoryAsParam = [NSArray arrayWithObjects:documentsDirectory, nil];

[JXcore callEventCallback:@"SetProcessCWD" withParams:directoryAsParam]; 

```

And then in JS land:

``` javascript
var setProcessCwd = function(cwdPath) {
    process.cwd = function(){
        return cwdPath+'/jxcore';
    }
}
JXmobile('SetProcessCWD').register(setProcessCwd);
```

But using process.userPath or require('os').tmpdir() will probably be better
